name: mt_map
description: A Flutter plugin for integrating Meituan Map SDK on iOS and Android platforms.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.mt_map
        pluginClass: MtMapPlugin
      ios:
        pluginClass: MtMapPlugin
